### ISSUE TITLE
RQ-Dashboard can no longer be integrated with Flask 2.3+ as a blueprint

### ISSUE THREAD

**Issue by born2discover** [eoranged/rq-dashboard#417]
Hello,

`app.before_first_request` and `blueprint.before_first_request` have been deprecated in Flask `2.2.0`  (https://github.com/pallets/flask/issues/4605) and completely removed in version `2.3.0`.

Therefore it is no longer possible for projects using Flask `2.3.0` to integrate rq-dashboard directly as an application blueprint. An attempt to do so will produce an `AttributeError: 'Blueprint' object has no attribute 'before_app_first_request'`.

**Comment by kennysong** [comment]
Our team has run into the same issue.

**Comment by mbhagdev** [comment]
Any workarounds or alternatives someone have for this issue?

**Comment by ArashHosseini** [comment]
+1

**Comment by kennysong** [comment]
@mbhagdev I saw that you seem to [have a fork of RQ Dashboard](https://github.com/mbhagdev/rq-dashboard) – does your fork fix this issue?

**Comment by mbhagdev** [comment]
> @mbhagdev I saw that you seem to [have a fork of RQ Dashboard](https://github.com/mbhagdev/rq-dashboard) – does your fork fix this issue?
Yes, I removed the annotation in question and called it in when loading flask app
I have a PR to be merged back in https://github.com/Parallels/rq-dashboard/pull/419
For usage in another flask app make sure to call that method now since its not automatically called like below using your flask app
```
app.config.setdefault('RQ_DASHBOARD_REDIS_URL', redis_url)
rq_dashboard.web.setup_rq_connection(app)
```

My fork is also published on pypi as rq-dashboard-compatible
`pip install rq-dashboard-compatible`

**Comment by kennysong** [comment]
Thanks @mbhagdev, confirmed that your fork works with flask==2.3.2!

Our team has created a separate fork internally that branches off of the 0.6.1 tag with the same changes, since your fork is based on master which has a [completely different](https://github.com/Parallels/rq-dashboard/issues/407) and new (?) UI.

**Comment by zhangguoqiang666** [comment]
+1

**Comment by zhangguoqiang666** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/rq-dashboard", line 5, in <module>
    from rq_dashboard.cli import main
  File "/usr/local/lib/python3.8/dist-packages/rq_dashboard/__init__.py", line 3, in <module>
    from .web import blueprint
  File "/usr/local/lib/python3.8/dist-packages/rq_dashboard/web.py", line 68, in <module>
    @blueprint.before_app_first_request
AttributeError: 'Blueprint' object has no attribute 'before_app_first_request'

**Comment by cjlapao** [comment]
This should now be fixed with the latest merge, please confirm

**Comment by AriefBadal23** [comment]
I'm still getting the same error.

> This should now be fixed with the latest merge, please confirm

**Comment by cjlapao** [comment]
@AriefBadal23  did you compile it from the source or did you use the releases? we did not update the releases, just the source

**Comment by AriefBadal23** [comment]
> @AriefBadal23 did you compile it from the source or did you use the releases? we did not update the releases, just the source

Oh I checked the released version,  I will try the source then.

**Comment by cjlapao** [comment]
@AriefBadal23 yes, the version has not been updated yet. we are working on automating this, will let you know once that automation if finalized, for now please use the source code

**Comment by mattiadri** [comment]
This worked for me
>pip install rq-dashboard-compatible

**Comment by cjlapao** [comment]
@AriefBadal23 we have now the PyPi package updated, so you should be all fine. Update to the latest 0.6.6
